### ISSUE TITLE
DEVNET-1 v4 - SDK v0.50: Gas simulating bug

### ISSUE THREAD

**Issue by RaulBernal** [BitCannaGlobal/BCNA#432]
Chain: DEVNET-1
BCNAD version: v4.0.0-rc4

In DEVNET-1 when you try to simulate gas in any TX you get this error:
`bcnad tx gov vote 34 yes --from resources --gas auto --gas-adjustment 2 --gas-prices 0.001ubcna`  (tested with other commands)
```go
Usage:
  bcnad tx gov vote [proposal-id] [option] [flags]

Flags:
  -a, --account-number uint      The account number of the signing account (offline mode only)
      --aux                      Generate aux signer data instead of sending a tx
  -b, --broadcast-mode string    Transaction broadcasting mode (sync|async) (default "sync")
      --chain-id string          The network chain ID
      --dry-run                  ignore the --gas flag and perform a simulation of a transaction, but don't broadcast it (when enabled, the local Keybase is not accessible)
      --fee-granter string       Fee granter grants fees for the transaction
      --fee-payer string         Fee payer pays fees for the transaction instead of deducting from the signer
      --fees string              Fees to pay along with transaction; eg: 10uatom
      --from string              Name or address of private key with which to sign
      --gas string               gas limit to set per-transaction; set to "auto" to calculate sufficient gas automatically. Note: "auto" option doesn't always report accurate results. Set a valid coin value to adjust the result. Can be used instead of "fees". (default 200000)
      --gas-adjustment float     adjustment factor to be multiplied against the estimate returned by the tx simulation; if the gas limit is set manually this flag is ignored  (default 1)
      --gas-prices string        Gas prices in decimal format to determine the transaction fee (e.g. 0.1uatom)
      --generate-only            Build an unsigned transaction and write it to STDOUT (when enabled, the local Keybase only accessed when providing a key name)
  -h, --help                     help for vote
      --keyring-backend string   Select keyring's backend (os|file|kwallet|pass|test|memory) (default "os")
      --keyring-dir string       The client Keyring directory; if omitted, the default 'home' directory will be used
      --ledger                   Use a connected Ledger device
      --metadata string          Specify metadata of the vote
      --node string              <host>:<port> to CometBFT rpc interface for this chain (default "tcp://localhost:26657")
      --note string              Note to add a description to the transaction (previously --memo)
      --offline                  Offline mode (does not allow any online functionality)
  -o, --output string            Output format (text|json) (default "json")
  -s, --sequence uint            The sequence number of the signing account (offline mode only)
      --sign-mode string         Choose sign mode (direct|amino-json|direct-aux|textual), this is an advanced feature
      --timeout-height uint      Set a block timeout height to prevent the tx from being committed past a certain height
      --tip string               Tip is the amount that is going to be transferred to the fee payer on the target chain. This flag is only valid when used with --aux, and is ignored if the target chain didn't enable the TipDecorator
  -y, --yes                      Skip tx broadcasting prompt confirmation

Global Flags:
      --home string         directory for config and data (default "/home/raul/.bcna")
      --log_format string   The logging format (json|plain) (default "plain")
      --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic|disabled or '*:<level>,<key>:<level>') (default "info")
      --log_no_color        Disable colored logs
      --trace               print out full stack trace on errors

rpc error: code = Unknown desc = rpc error: code = Unknown desc = recovered: runtime error: invalid memory address or nil pointer dereference
stack:
goroutine 54007476 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:26 +0x5e
github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func5({0x2c9f2c0, 0x5a54890})
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/baseapp/recovery.go:74 +0x25
github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func7({0x2c9f2c0?, 0x5a54890?})
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/baseapp/recovery.go:42 +0x2d
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x2c9f2c0, 0x5a54890}, 0x0?)
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/baseapp/recovery.go:31 +0x2f
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x2c9f2c0, 0x5a54890}, 0x0?)
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/baseapp/recovery.go:36 +0x53
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/baseapp/baseapp.go:842 +0x12c
panic({0x2c9f2c0?, 0x5a54890?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
github.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle.func1()
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/x/auth/ante/setup.go:65 +0x1fb
panic({0x2c9f2c0?, 0x5a54890?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
github.com/CosmWasm/wasmd/x/wasm/keeper.LimitSimulationGasDecorator.AnteHandle({_}, {{0x3e956c0, 0x5c19e40}, {0x3eb2200, 0xc017875b40}, {{0x0, 0x0}, {0xc002325500, 0xe}, 0x95640a, ...}, ...}, ...)
	/home/raul/go/pkg/mod/github.com/!cosm!wasm/wasmd@v0.53.0/x/wasm/keeper/ante.go:103 +0xf7
github.com/BitCannaGlobal/bcna/app.NewAnteHandler.ChainAnteDecorators.func2({{0x3e956c0, 0x5c19e40}, {0x3eb2200, 0xc017875b40}, {{0x0, 0x0}, {0xc002325500, 0xe}, 0x95640a, {0xa52194f, ...}, ...}, ...}, ...)
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/types/handler.go:48 +0x105
github.com/cosmos/cosmos-sdk/x/auth/ante.SetUpContextDecorator.AnteHandle({}, {{0x3e956c0, 0x5c19e40}, {0x3eb2200, 0xc017875b40}, {{0x0, 0x0}, {0xc002325500, 0xe}, 0x95640a, ...}, ...}, ...)
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/x/auth/ante/setup.go:70 +0x7e6
github.com/BitCannaGlobal/bcna/app.NewAnteHandler.ChainAnteDecorators.func2({{0x3e956c0, 0x5c19e40}, {0x3eb2200, 0xc017875b40}, {{0x0, 0x0}, {0xc002325500, 0xe}, 0x95640a, {0xa52194f, ...}, ...}, ...}, ...)
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/types/handler.go:48 +0x105
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc000e74b48, 0x2, {0xc0033669c0, 0xb3, 0xc0})
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/baseapp/baseapp.go:905 +0x97f
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(...)
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/baseapp/test_helpers.go:28
github.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x3ebab90, 0xc0047a7320}, 0x0, {0xc0010d6c00, 0xe}, {0x3edb370, 0xc000689ef0}, ...}, ...}, ...)
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/x/auth/tx/service.go:98 +0x12c
github.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x3027400, 0xc000734b40}, {0x3e956f8, 0xc003377508}, 0xc0064fa8d0, 0x0)
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/types/tx/service.pb.go:1436 +0x1a6
github.com/cosmos/cosmos-sdk/baseapp.(*GRPCQueryRouter).registerABCIQueryHandler.func1({{0x3e956c0, 0x5c19e40}, {0x3eb2200, 0xc017875a40}, {{0x0, 0x0}, {0xc002325500, 0xe}, 0x95640a, {0xa52194f, ...}, ...}, ...}, ...)
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/baseapp/grpcrouter.go:109 +0xcf
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC(0xc000e74b48, 0xc0047a7350, 0xc00b8b81c0)
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/baseapp/abci.go:1142 +0x19d
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0xc000e74b48, {0xc0035b4cd0?, 0x4145a5?}, 0xc00b8b81c0)
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/baseapp/abci.go:177 +0x618
github.com/cosmos/cosmos-sdk/server.cometABCIWrapper.Query(...)
	/home/raul/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/server/cmt_abci.go:24
github.com/cometbft/cometbft/abci/client.(*localClient).Query(0xc000b319e0?, {0x3e95998?, 0x5c19e40?}, 0x7f1a5c45b878?)
	/home/raul/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/abci/client/local_client.go:106 +0xc7
github.com/cometbft/cometbft/proxy.(*appConnQuery).Query(0xc001969f08, {0x3e95998, 0x5c19e40}, 0xc00b8b81c0)
	/home/raul/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/proxy/app_conn.go:181 +0x162
github.com/cometbft/cometbft/rpc/core.(*Environment).ABCIQuery(0xc000e74488, 0xc007929050?, {0xc022d80b10, 0x23}, {0xc003366900, 0xb6, 0xb6}, 0x0, 0x0)
	/home/raul/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/rpc/core/abci.go:22 +0xd0
reflect.Value.call({0x2d11e80?, 0xc001153ba0?, 0x31766c0?}, {0x3183d56, 0x4}, {0xc024dd7000, 0x5, 0x5?})
	/usr/local/go/src/reflect/value.go:581 +0xca6
reflect.Value.Call({0x2d11e80?, 0xc001153ba0?, 0x1bf?}, {0xc024dd7000?, 0x31766c0?, 0x1?})
	/usr/local/go/src/reflect/value.go:365 +0xb9
github.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.makeJSONRPCHandler.func3({0x3e89150, 0xc001697500}, 0xc0025e6dc0)
	/home/raul/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/rpc/jsonrpc/server/http_json_handler.go:108 +0xcd0
github.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.handleInvalidJSONRPCPaths.func4({0x3e89150?, 0xc001697500?}, 0x47375d?)
	/home/raul/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/rpc/jsonrpc/server/http_json_handler.go:140 +0x42
net/http.HandlerFunc.ServeHTTP(0xc002542460?, {0x3e89150?, 0xc001697500?}, 0xc00db3d1e0?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
net/http.(*ServeMux).ServeHTTP(0xc000f3cdd0?, {0x3e89150, 0xc001697500}, 0xc0025e6dc0)
	/usr/local/go/src/net/http/server.go:2747 +0x1ca
github.com/cometbft/cometbft/node.(*Node).startRPC.(*Cors).Handler.func9({0x3e89150, 0xc001697500}, 0xc0025e6dc0)
	/home/raul/go/pkg/mod/github.com/rs/cors@v1.11.1/cors.go:289 +0x184
net/http.HandlerFunc.ServeHTTP(0xd?, {0x3e89150?, 0xc001697500?}, 0x3193ac1?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
github.com/cometbft/cometbft/rpc/jsonrpc/server.defaultHandler.ServeHTTP(...)
	/home/raul/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/rpc/jsonrpc/server/http_server.go:259
github.com/cometbft/cometbft/rpc/jsonrpc/server.Serve.RecoverAndLogHandler.func1({0x3e84fc0, 0xc0022bc2a0}, 0xc0025e6dc0)
	/home/raul/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/rpc/jsonrpc/server/http_server.go:234 +0x233
net/http.HandlerFunc.ServeHTTP(0x3e5b380?, {0x3e84fc0?, 0xc0022bc2a0?}, 0x2b52cc0?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
github.com/cometbft/cometbft/rpc/jsonrpc/server.Serve.PreChecksHandler.func2({0x3e84fc0, 0xc0022bc2a0}, 0xc0025e6dc0)
	/home/raul/go/pkg/mod/github.com/cometbft/cometbft@v0.38.12/rpc/jsonrpc/server/http_server.go:327 +0x10c
net/http.HandlerFunc.ServeHTTP(0x4145a5?, {0x3e84fc0?, 0xc0022bc2a0?}, 0xc0022bc201?)
	/usr/local/go/src/net/http/server.go:2220 +0x29
net/http.serverHandler.ServeHTTP({0x3e6eac8?}, {0x3e84fc0?, 0xc0022bc2a0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3210 +0x8e
net/http.(*conn).serve(0xc02e283710, {0x3e958b8, 0xc003085f20})
	/usr/local/go/src/net/http/server.go:2092 +0x5d0
created by net/http.(*Server).Serve in goroutine 193
	/usr/local/go/src/net/http/server.go:3360 +0x485
: panic [cosmos/cosmos-sdk@v0.50.9/baseapp/recovery.go:72] with gas used: '1027': unknown request
```

**Comment by RaulBernal** [comment]
Solved by https://github.com/BitCannaGlobal/bcna/issues/425
